export const i18n = {
  zh: {
    nav: { lineup: "演出陣容", schedule: "演出時間表", info: "活動資訊", credits: "工作人員" },
    hero: {
      title: "TAIWANESE FUN",
      titleShort: "T FUN",
      subtitle: "音樂祭",
      date: "2026 / 07 / 25（六）14:00 開始",
      venue: "GR.iD Singapore",
      address: "1 Selegie Road, B1-06, 188306",
      cta: "查看陣容",
    },
    lineup: {
      sectionLabel: "LINEUP",
      sectionTitle: "演出陣容",
      members: "成員",
      songs: "演出曲目",
      viewAll: "查看完整陣容",
      back: "返回首頁",
    },
    info: {
      sectionLabel: "INFO",
      sectionTitle: "活動資訊",
      dateLabel: "日期",
      dateValue: "2026 年 7 月 25 日（週六）14:00 開始",
      venueLabel: "地點",
      venueValue: "GR.iD Singapore",
      addressLabel: "地址",
      addressValue: "1 Selegie Road, B1-06, 188306",
      mapLink: "在 Google Maps 中開啟",
    },
    credits: {
      sectionLabel: "CREDITS",
      sectionTitle: "工作人員",
    },
    menu: "選單",
    lang: "EN",
  },
  en: {
    nav: { lineup: "Lineup", schedule: "Schedule", info: "Info", credits: "Credits" },
    hero: {
      title: "TAIWANESE FUN",
      titleShort: "T FUN",
      subtitle: "MUSIC FEST",
      date: "2026 / 07 / 25 (SAT) from 2:00 PM",
      venue: "GR.iD Singapore",
      address: "1 Selegie Road, B1-06, 188306",
      cta: "View Lineup",
    },
    lineup: {
      sectionLabel: "LINEUP",
      sectionTitle: "Performing Artists",
      members: "Members",
      songs: "Setlist",
      viewAll: "View Full Lineup",
      back: "Back to Home",
    },
    info: {
      sectionLabel: "INFO",
      sectionTitle: "Event Info",
      dateLabel: "Date",
      dateValue: "July 25, 2026 (Saturday) from 2:00 PM",
      venueLabel: "Venue",
      venueValue: "GR.iD Singapore",
      addressLabel: "Address",
      addressValue: "1 Selegie Road, B1-06, 188306",
      mapLink: "Open in Google Maps",
    },
    credits: {
      sectionLabel: "CREDITS",
      sectionTitle: "Staff",
    },
    menu: "Menu",
    lang: "中",
  },
};

export const bands = [
  {
    id: 1,
    name: "VINKH JAMMING 果醬樂隊",
    genre: "M-POP / J-ROCK",
    images: ["Kaho.jpeg", "Nick.jpg", "Vivian.jpg"],
    members: {
      zh: "Vocal: Nick ／ Guitar: Kaho ／ Drum: Vivian",
      en: "Vocal: Nick / Guitar: Kaho / Drum: Vivian",
    },
    songs: ["浪子回頭", "灌籃高手 - 好想大聲說喜歡你", "Without You"],
    color: "#39FF14",
  },
  {
    id: 8,
    name: "Babyblade <3",
    genre: "PUNK / POP",
    homeImage: "Babyblade.png",
    images: ["Babyblade.png", "Darren.png", "Dean.png", "Perry.png"],
    members: {
      zh: "Vocal: Dean／ Bass: Dean ／ Guitar: Darren ／ Drum: Perry",
      en: "Vocal: Dean / Bass: Dean / Guitar: Darren / Drum: Perry",
    },
    songs: [
      "透明雜誌 - 透明雜誌Forever",
      "拍謝少年 - 歹勢中年",
      "拍謝少年 - 噪音公寓",
    ],
    color: "#FF003C",
  },
  {
    id: 3,
    name: "AFteR",
    genre: "MANDOPOP",
    images: ["Aries.jpeg", "Frida.jpeg", "RueiYi.jpeg"],
    members: {
      zh: "Vocal: Frida ／ Guitar: Rui-Yi ／ Others: 鎮宇",
      en: "Vocal: Frida / Guitar: Rui-Yi / Others: Zhen-Yu",
    },
    songs: ["F.I.R - 星火", "怕胖團 - 魚", "自創曲"],
    color: "#FF69B4",
  },
  {
    id: 4,
    name: "歹灣郎宮廟總會",
    genre: "DANCE",
    duration: 10,
    images: ["dancingclub.png", "sun.jpg", "Lynn.jpg"],
    members: {
      zh: "YuFeng ／ 安 ／ Dio ／ Lynn ／ Ty ／ Winney ／ Sun ／ 得瑋 — 熱舞社",
      en: "Yu-Feng / An / Dio / Lynn / Ty / Winney / Sun / De-Wei — Dance Crew",
    },
    songs: [],
    color: "#BF00FF",
  },
  {
    id: 5,
    name: "Grace後援會",
    genre: "STRINGS",
    duration: 20,
    images: ["Swenson.jpg", "GraceClub.jpg"],
    members: {
      zh: "頌缽：Jinghan ／ Grace ／ Swenson ／ Greta",
      en: "Singing Bowl: Jinghan / Grace / Swenson / Greta",
    },
    songs: ["島嶼共振：頌缽鳴心 (Island Resonance)"],
    color: "#00FFFF",
  },
  {
    id: 6,
    name: "PASH",
    genre: "ORIGINAL",
    images: ["PASH.png"],
    members: {
      zh: "Vocal: PASH ／ Guitar: Kaho",
      en: "Vocal: PASH / Guitar: Kaho",
    },
    songs: [
      "我是一隻鹹魚嗎？ Am I a Salted Fish?",
      "有時 Sometimes",
      "揮霍 Squandering",
    ],
    color: "#FF6600",
  },
  {
    id: 7,
    name: "降什麼Key Lah",
    genre: "MANDOPOP",
    homeImage: "whatkey.jpg",
    images: ["whatkey.jpg"],
    members: {
      zh: "Vocal: Yanrong ／ Guitar: Brian ／ Drum: Jason ／ Bass: John",
      en: "Vocal: Yanrong / Guitar: Brian / Drum: Jason / Bass: John",
    },
    songs: ["A-Lin - 摯友", "理想混蛋 - 不是因為天氣晴朗才愛你", "F.I.R - 月牙灣"],
    color: "#39FF14",
  },
  {
    id: 2,
    name: "Jamie Band",
    genre: "MANDOPOP",
    members: {
      zh: "Vocal: Jamie ／ Guitar: Darren ／ Drum: Aries",
      en: "Vocal: Jamie / Guitar: Darren / Drum: Aries",
    },
    songs: ["Creep", "傷痕", "Fall in love alone"],
    color: "#FFFF00",
  },
  {
    id: 9,
    name: "LB Violin Sisters",
    genre: "STRINGS",
    members: {
      zh: "敬請期待",
      en: "Coming soon",
    },
    songs: [],
    color: "#00E5FF",
  },
  {
    id: 10,
    name: "One Tannery 壹號皮革廠",
    genre: "BAND",
    members: {
      zh: "敬請期待",
      en: "Coming soon",
    },
    songs: [],
    color: "#FF7A00",
  },
];

export const staff = [
  { role: "總召 / 活動統籌 / 舞台監督 / 視覺設計 / 票務統籌", roleEn: "Lead / Event Coordinator / Stage Director / Visual Design / Ticketing", name: "Nick" },
  { role: "音控 / 場地", roleEn: "Sound / Venue", name: "Phil Studio" },
];

export const noiseSVG = `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.04'/%3E%3C/svg%3E")`;
